run:
  timeout: 5m
  skip-dirs:
    - vendor
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - typecheck  # Отключаем проблемный линтер

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
