all:
  children:
    production:
      hosts:
        myapp:
          ansible_host: 185.40.76.46
          ansible_user: test
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/python3
