---
# Common settings
app_name: myapp
app_dir: "/home/{{ ansible_user }}/myapp"
domain: mvp2001.ru

# Docker
docker_version: "24.0.7"
docker_compose_version: "2.23.0"

# Database
db_name: devops_app
db_user: appuser
db_password: "{{ vault_db_password }}"  # будем шифровать

# Vault
vault_token: devroot
